github:
  description: Apache ECharts MCP Server
  homepage: https://github.com/apache/echarts-mcp
  labels:
    - echarts
    - mcp
    - data-visualization

notifications:
  commits: commits@echarts.apache.org
  pullrequests: commits@echarts.apache.org
  issues: commits@echarts.apache.org
